services:
  ittt_bot_web:
    image: ghcr.io/${REPO_OWNER}/ittt-bot:${IMAGE_TAG}
    ports:
      - "9000:9000"
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  db:
    image: postgres:17.5
    volumes:
      - ittt_bot_pgdata:/var/lib/postgresql/ittt_bot_data
    env_file:
      - .env
    restart: always

volumes:
  ittt_bot_pgdata: