services:
  iiit_bot_web:
    image: ghcr.io/${REPO_OWNER}/ittt-bot:${IMAGE_TAG}
    expose:
      - "9000"           # expose to other containers, but no host binding
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  db:
    image: postgres:17.5
    volumes:
      - iiit_bot_pgdata:/var/lib/postgresql/iiit_bot_data
    env_file:
      - .env
    restart: always

volumes:
  iiit_bot_pgdata: